name: cooking_calulator
description: Unit converter and amount calculator for cook
version: 0.2.0+0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # layers
  data:
    path: ./data

  # state management
  flutter_riverpod: ^2.1.3

  # annotation

  # database
  collection: ^1.16.0
  isar_flutter_libs: ^3.0.5
  path_provider: ^2.0.14
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # linter
  flutter_lints: ^2.0.1

  # code generator
  build_runner: ^2.1.8
  json_serializable: ^6.1.6
  freezed: ^2.3.5
  riverpod_lint: ^1.3.2
  custom_lint: ^0.4.0
  mockito: ^5.4.2
  isar: ^3.1.0+1

flutter:
  uses-material-design: true
