name: cooking_calulator
description: Unit converter and amount calculator for cook
version: 0.1.0+0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State management
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.3

  # annotation
  freezed_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # linter
  flutter_lints: ^2.0.1

  # code generator
  build_runner: ^2.1.8
  freezed: ^2.0.0
  json_serializable: ^6.1.6
